apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: ${REGISTRY_HOST}/jupyterhub
    kaniko:
      cache: {}
  cluster:
    serviceAccount: kaniko
    dockerConfig:
      path: ~/.docker/config.json
deploy:
  kustomize: {}
