apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-03
spec:
  vendor: eduk8s.io
  title: "Jupyter on Kubernetes #3"
  description: A workshop exploring using JupyterHub to deploy Jupyter notebooks to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-03
  content:
    files: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-03
  duration: 45m
  session:
    budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
    resources:
      limits:
        memory: 768Mi
    ingresses:
    - name: local-8000
      port: 8000
    - name: local-8001
      port: 8001
    - name: local-8081
      port: 8081
    - name: local-8888
      port: 8888
