apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-03
spec:
  vendor: eduk8s.io
  title: "Jupyter on Kubernetes #3"
  description: A workshop exploring using JupyterHub to deploy Jupyter notebooks to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-03
  content:
    files: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-03
  duration: 45m
  session:
    budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
    resources:
      limits:
        memory: 768Mi
    ingresses:
    - name: local-8000
      port: 8000
    objects:
    - apiVersion: v1
      kind: Service
      metadata:
        name: $(session_namespace)-jupyterhub
      spec:
        type: ClusterIP
        selector:
          deployment: $(session_namespace)
        ports:
        - name: 8001-tcp
          port: 8001
          protocol: TCP
          targetPort: 8001
