apiVersion: v1
kind: Service
metadata:
  name: jupyterhub
spec:
  ports:
  - name: 8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: 8001-tcp
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    deployment: jupyterhub
