apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- rolebinding.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
- name: jupyterhub
  files:
    - jupyterhub_config.py

